"""Add is_public field to KnowledgeDocument

Revision ID: 26ba5f2623e7
Revises: 7028eeb26a55
Create Date: 2025-04-15 18:13:07.835385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ba5f2623e7'
down_revision = '7028eeb26a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
